sudo: required
services:
  - docker

script:
  - docker build -t itsmekhmtz/node .
  - docker images itsmekhmtz/node

before_deploy:
  - docker login -u itsmekhmtz -p 3Tw*YaY*w-Q-qZL

deploy:
  provider: script
  script: docker push itsmekhmtz/test_travis1:node
  on:
    branch: master